# Generated by Django 5.2.10 on 2026-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfPsy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('photo', models.ImageField(upload_to='')),
                ('desc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='emp_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telephonenumber', models.CharField(max_length=80)),
                ('specialite', models.CharField(max_length=100)),
                ('localisation_cabinet', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient_insc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('my_email', models.EmailField(default='', max_length=100)),
                ('my_password', models.CharField(max_length=30)),
                ('passw', models.CharField(max_length=30)),
                ('Sexe', models.CharField(default='', max_length=1)),
                ('NumTel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='psy_insc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('passw', models.CharField(max_length=30)),
                ('fichiers', models.FileField(upload_to='fichiers')),
            ],
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('email', models.EmailField(default='', max_length=100)),
                ('DocName', models.CharField()),
            ],
        ),
    ]
