# Generated by Django 5.2.10 on 2026-08-13 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('cabinet', 'Au cabinet'), ('teleconsultation', 'Téléconsultation')], default='cabinet', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='psy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.psy_insc'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.medecin'),
        ),
    ]
