# Generated by Django 5.2.10 on 2026-08-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='new_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_requested_by',
            field=models.CharField(blank=True, choices=[('medecin', 'Médecin'), ('psy', 'Psychologue'), ('patient', 'Patient')], max_length=10, null=True),
        ),
    ]
